### ISSUE TITLE
Dataset missing

### ISSUE THREAD

**Issue by bentoayr** [PredictiveIntelligenceLab/LOCA#1]
Hello,

Your results are not reproducible.

Data set files missing, for example, train_SW.npz  and /train_darcy_dataset.npz .

Google drive links not working.

Can you fix this.

Many thanks !

**Comment by hieronimoDos** [comment]
Hi,

I am sorry for the inconvenience. I finished my PhD and my google account affiliated with UPenn got deleted, which is why the link is not working. I will upload a new link as soon as possible.

**Comment by bentoayr** [comment]
Great, looking forward to it !

**Comment by bentoayr** [comment]
Can you give me an ETA on this?

**Comment by hieronimoDos** [comment]
I have updated the repo. Sorry for the delay, but it took me a while to find these files and upload to a new drive. I believe that these are the correct ones. 

I am going to close this thread. Please send me an email directly to gkissas@ai.ethz.ch if you have more questions or concerns. 

Sounds good?
